
import Head from 'next/head'
import { Grid } from '../layout/Grid'
interface IWebsitePages {
  children: React.ReactNode,
  footerProps: boolean,
}
export default function WebsitePages ({
  children,
  footerProps
}: IWebsitePages) {
  return (
    <div>
      <Head>
        <title>Encript/Decrypt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid.Container justifyContent='center'>
          {children}    
        </Grid.Container>
      </main>

      {footerProps && <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span>
            Feito com :love: Por Max Milliano
          </span>
        </a>
      </footer>}
    </div>
  )
}

WebsitePages.defaultProps = {
  footerProps: true
}